version: "3.9"
services:
  db:
    build: ./db-dockerfile
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - db-network
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

networks:
  db-network:
    driver: bridge
