version: "3.8"
services:
  backend:
    image: "kuan1025/springboot-react-fullstack:15.12.2024.0.41.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

