version: "3.8"
services:
  backend:
    image: "kuan1025/springboot-react-fullstack:10.12.2024.3.56.51"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

