version: "3.8"
services:
  backend:
    image: "kuan1025/springboot-react-fullstack:12.12.2024.11.39.49"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

